// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function problemtwo(n) {
  let sum = 0;
  let arr = [1, 2];

  //create a Fib sequence array that is limited to being under the input number value

  for (let i = 0; arr[i + 1] < n; i++) {
    arr.push(arr[i] + arr[i + 1]);
  }

  //loop through array to add only even numbers

  for (let j = 0; j < arr.length; j++) {
    if (arr[j] % 2 == 0) {
      sum += arr[j];
    }
  }
  //   console.log("array:", arr);
  console.log("sum:", sum);
}

problemtwo(10);
